replicaCount: 2

image:
  repository: nginx
  tag: 1.27.4
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

service:
  type: LoadBalancer
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpuPercentage: 70